apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: terceiro-pod
spec:
  containers:
    - name: container-pod-3
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"